# Generated by Django 4.1 on 2023-05-12 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("deposit", models.FloatField()),
                ("name", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Time", models.DateTimeField()),
                ("Recipient", models.CharField(max_length=45)),
                ("Amount", models.IntegerField()),
                ("Money", models.FloatField()),
                ("secret_key", models.CharField(max_length=45)),
                ("Airline_order", models.CharField(max_length=45)),
                ("State", models.BooleanField()),
                (
                    "User_Id",
                    models.ForeignKey(
                        db_column="User_Id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
